database: &database
  adapter: postgresql
  host: localhost
  port: 5432
  timeout: 5000
  schema_search_path: "sequent_schema, view_schema"

development:
  <<: *database
  pool: 5
  database: user_development

test:
  <<: *database
  pool: 5
  database: user_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  schema_search_path: "sequent_schema, view_schema"